name: Chore
description: 非 Bug 或是 Feature 的工作 / Non Bug or Feature work
title: Chore - Title
labels: [documentation, chore]
body:
  - type: textarea
    attributes:
      label: 從事內容 / Description
      description: 簡單描述內容
      render: markdown
  - type: textarea
    attributes:
      label: 預期效果 / Expected Behavior
      description: 描述預期效果
      render: markdown
  - type: textarea
    attributes:
      label: 其他補充
      description: |
        任何連結、截圖或影片等補充訊息，都可以寫在這裡。
        Any additional information, such as links, screenshots, or videos, can be written here.
        提示：可以點擊此區域以突出顯示，然後拖入圖片或相關文件。
        Tip: You can click this area to highlight it, and then drag in images or relevant files.
