name: Feature Request
description: 提交一個新功能的需求 / Request a new feature
title: Feature - Title
labels: [feature]
body:
  - type: textarea
    attributes:
      label: 需求內容 / Description
      description: 簡單描述需求
      render: markdown
  - type: textarea
    attributes:
      label: 預期效果 / Expected Behavior
      description: 簡單描述預期效果
      render: markdown
  - type: textarea
    attributes:
      label: 其他補充 / Additional Information
      description: |
        任何連結、截圖或影片等補充訊息，都可以寫在這裡。
        Any additional information, such as links, screenshots, or videos, can be written here.
        提示：可以點擊此區域以突出顯示，然後拖入圖片或相關文件。
        Tip: You can click this area to highlight it, and then drag in images or relevant files.
